export const SELECT_OPTION = 'SELECT_OPTION';
export const SELECT_YEAR = 'SELECT_YEAR';

export const FETCH_BUBBLES = 'FETCH_BUBBLES';
export const FETCH_BUBBLES_FAILED = 'FETCH_BUBBLES_FAILED';
export const FETCH_BUBBLES_SUCCEEDED = 'FETCH_BUBBLES_SUCCEEDED';
