export const BUBBLES_SELECT_OPTION = 'BUBBLES_SELECT_OPTION';
export const BUBBLES_SELECT_YEAR = 'BUBBLES_SELECT_YEAR';
export const BUBBLES_TOGGLE_HIGHLIGHTING = 'BUBBLES_TOGGLE_HIGHLIGHTING';

export const BUBBLES_FETCH = 'BUBBLES_FETCH';
export const BUBBLES_FETCH_FAILED = 'BUBBLES_FETCH_FAILED';
export const BUBBLES_FETCH_SUCCEEDED = 'BUBBLES_FETCH_SUCCEEDED';
