export const PARTIES_SELECT_OPTION = 'PARTIES_SELECT_OPTION';
export const PARTIES_TOGGLE_HIGHLIGHTING = 'PARTIES_TOGGLE_HIGHLIGHTING';

export const PARTIES_FETCH = 'PARTIES_FETCH';
export const PARTIES_FETCH_FAILED = 'PARTIES_FETCH_FAILED';
export const PARTIES_FETCH_SUCCEEDED = 'PARTIES_FETCH_SUCCEEDED';
