export const SELECT_DOMAIN = 'SELECT_DOMAIN';

export const FETCH_QUERY = 'FETCH_QUERY';
export const FETCH_QUERY_FAILED = 'FETCH_QUERY_FAILED';
export const FETCH_QUERY_SUCCEEDED = 'FETCH_QUERY_SUCCEEDED';
